name: Build HttpTriggerPostExperiment

on:
  workflow_call:

env:
  KUI_SOLUTION: HttpPostExperiment.sln
  KUI_SOLUTION_BUILD_CONFIGURATION: Release
  KUI_SOLUTION_WORK_PATH: ${{ github.workspace }}/http_post_exp_function_app
  KUI_SOLUTION_ARTIFACTS_PATH: ${{ github.workspace }}/artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Dotnet Clean
        run: dotnet clean ${{ env.KUI_SOLUTION }}
      - name: Dotnet Restore
        run: dotnet restore ${{ env.KUI_SOLUTION }}
      - name: Dotnet Build
        run: dotnet build ${{ env.KUI_SOLUTION }} -c ${{ env.KUI_SOLUTION_BUILD_CONFIGURATION }} --no-restore
