name: Build HttpTriggerPostExperiment

on:
  workflow_call:
    inputs:
      KUI_SOLUTION_WORK_PATH:
        required: true
        type: string
      KUI_SOLUTION_ARTIFACTS_PATH:
        required: true
        type: string
      KUI_ARTIFACT_RELEASE_PATH:
        required: true
        type: string
      KUI_SOLUTION:
        required: true
        type: string
      KUI_SOLUTION_BUILD_CONFIGURATION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KUI_SOLUTION_WORK_PATH: ${{ inputs.KUI_SOLUTION_WORK_PATH }}
      KUI_SOLUTION_ARTIFACTS_PATH: ${{ inputs.KUI_SOLUTION_ARTIFACTS_PATH }}
      KUI_ARTIFACT_RELEASE_PATH: ${{ inputs.KUI_ARTIFACT_RELEASE_PATH }}
      KUI_SOLUTION: ${{ inputs.KUI_SOLUTION }}
      KUI_SOLUTION_BUILD_CONFIGURATION: ${{ inputs.KUI_SOLUTION_BUILD_CONFIGURATION }}
    steps:
      - name: Print github.workspace
        run: echo "${{ github.workspace }}"
      - name: Print KUI_SOLUTION_WORK_PATH
        run: echo "${{ env.KUI_SOLUTION_WORK_PATH }}"
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare KUI_SOLUTION_WORK_PATH directory
        run: mkdir -p ${{ env.KUI_SOLUTION_WORK_PATH }}
      - name: Prepare KUI_SOLUTION_ARTIFACTS_PATH directory
        run: mkdir -p ${{ env.KUI_SOLUTION_ARTIFACTS_PATH }}
      - name: Prepare KUI_ARTIFACT_RELEASE_PATH directory
        run: mkdir -p ${{ env.KUI_ARTIFACT_RELEASE_PATH }}
      - name: Dotnet Clean
        run: dotnet clean ${{ env.KUI_SOLUTION }}
      - name: Dotnet Restore
        run: dotnet restore ${{ env.KUI_SOLUTION }}
      - name: Dotnet Build
        run: dotnet build ${{ env.KUI_SOLUTION }} -c ${{ env.KUI_SOLUTION_BUILD_CONFIGURATION }} --no-restore
