name: Build and Release Azure Function App

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Unit Tests
      run: dotnet test ${{ github.workspace }}/HttpTriggerPostExperimentTests/HttpTriggerPostExperimentTests.csproj --configuration Release

    - name: Build Project
      run: dotnet build ${{ github.workspace }}/HttpPostExperiment/HttpPostExperiment.csproj --output ${{ github.workspace }}/publish_output --configuration Release

    - name: Archive files
      run: |
        mkdir -p ${{ github.workspace }}/artifacts
        powershell Compress-Archive -Path ${{ github.workspace }}/publish_output\* -DestinationPath ${{ github.workspace }}/artifacts\drop.zip
        mkdir -p ${{ github.workspace }}/release
        Copy-Item -Path ${{ github.workspace }}/artifacts\drop.zip -Destination ${{ github.workspace }}/release\drop.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: ${{ github.workspace }}/release/drop.zip

    - name: Verify drop.zip exists
      run: |
        if (Test-Path "${{ github.workspace }}\release\drop.zip") {
          Write-Host "drop.zip exists"
        } else {
          Write-Host "drop.zip is missing"
          exit 1
        }

    - name: Install Azure CLI
      uses: azure/setup-cli@v1

    - name: Login to Azure DevOps
      run: |
        echo ${{ secrets.AZURE_DEVOPS_PAT }} | az devops login
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

    - name: Publish drop.zip to Azure Artifacts
      run: |
        az artifacts universal publish \
          --organization https://dev.azure.com/MariusRoosenschoon \
          --project "Sandpit" \
          --scope project \
          --feed My-GitHub-Feed \
          --name drop \
          --version 1.0.${{ github.run_number }} \
          --description "Function App deployment artifact" \
          --path ${{ github.workspace }}/release

        - name: List after build
          run: |
            cd ${{ github.workspace }}
            pwd
            Get-ChildItem -Recurse
