name: Build HttpTriggerPostExperiment

on:
  push:
    branches:
      - develop
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  KUI_SOLUTION: HttpPostExperiment.sln
  KUI_SOLUTION_PROJECT: HttpPostExperiment.csproj
  KUI_SOLUTION_BUILD_CONFIGURATION: Release
  KUI_SOLUTION_TEST_PROJECT: ${{ github.workspace }}/tests/HttpTriggerPostExperimentTests/HttpTriggerPostExperimentTests.csproj
  KUI_SOLUTION_SOURCE_PATH: ${{ github.workspace }}/src/functions/HttpPostExperiment
  KUI_SOLUTION_WORK_PATH: ${{ github.workspace }}/http_post_exp_function_app
  KUI_SOLUTION_BUILD_PATH: ${{ github.workspace }}/http_post_exp_function_app/build
  KUI_SOLUTION_ARTIFACTS_PATH: ${{ github.workspace }}/artifacts

  KUI_ARTIFACT_VERSION: 1.0.${{ github.run_number }}
  KUI_ARTIFACT_RELEASE_PATH: ${{ github.workspace }}/release
  KUI_ARTIFACT_ZIP_NAME: http-post-exp-fa-package

  KUI_SCRIPT_STAGE_1: ${{ github.workspace }}/release/Scripts/http-post-exp-stage-1.sh
  KUI_SCRIPT_STAGE_2: ${{ github.workspace }}/release/Scripts/http-post-exp-stage-2.sh
  KUI_SCRIPT_STAGE_3: ${{ github.workspace }}/release/Scripts/http-post-exp-stage-3.sh
  KUI_SCRIPT_STAGE_4: ${{ github.workspace }}/release/Scripts/http-post-exp-stage-4.sh

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: Development
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare KUI_SOLUTION_WORK_PATH directory
        run: mkdir -p ${{ env.KUI_SOLUTION_WORK_PATH }}
      - name: Prepare KUI_SOLUTION_ARTIFACTS_PATH directory
        run: mkdir -p ${{ env.KUI_SOLUTION_ARTIFACTS_PATH }}
      - name: Prepare KUI_ARTIFACT_RELEASE_PATH directory
        run: mkdir -p ${{ env.KUI_ARTIFACT_RELEASE_PATH }}
      - name: Dotnet Clean
        run: dotnet clean ${{ env.KUI_SOLUTION }}
      - name: Dotnet Restore
        run: dotnet restore ${{ env.KUI_SOLUTION }}
      - name: Dotnet Build
        run: dotnet build ${{ env.KUI_SOLUTION }} -c ${{ env.KUI_SOLUTION_BUILD_CONFIGURATION }} --no-restore
      - name: Run Unit Tests
        run: dotnet test ${{ env.KUI_SOLUTION_TEST_PROJECT }} --configuration ${{ env.KUI_SOLUTION_BUILD_CONFIGURATION }}
      - name: Copy function app files
        run: |
          mkdir -p ${{ env.KUI_SOLUTION_WORK_PATH }}/src/functions
          cp -a ${{ env.KUI_SOLUTION_SOURCE_PATH }} ${{ env.KUI_SOLUTION_WORK_PATH }}/src/functions/
      - name: Dotnet Restore
        run: dotnet restore ${{ env.KUI_SOLUTION_SOURCE_PATH }}/${{ env.KUI_SOLUTION_PROJECT }}
      - name: Dotnet Publish
        run: dotnet publish ${{ env.KUI_SOLUTION_SOURCE_PATH }}/${{ env.KUI_SOLUTION_PROJECT }} -c ${{ env.KUI_SOLUTION_BUILD_CONFIGURATION }} -o ${{ env.KUI_SOLUTION_BUILD_PATH }}
      - name: Create deployment package
        run: |
          cd ${{ env.KUI_SOLUTION_BUILD_PATH }}
          zip -r ${{ env.KUI_ARTIFACT_RELEASE_PATH }}/${{ env.KUI_ARTIFACT_ZIP_NAME }}_${{ env.KUI_ARTIFACT_VERSION }}.zip .
      - name: Copy Scripts to artifact release path
        run: |
          mkdir -p ${{ env.KUI_ARTIFACT_RELEASE_PATH }}/Scripts
          cp -a ${{ env.KUI_SOLUTION_SOURCE_PATH }}/Scripts/* ${{ env.KUI_ARTIFACT_RELEASE_PATH }}/Scripts/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KUI_ARTIFACT_ZIP_NAME }}
          path: ${{ env.KUI_ARTIFACT_RELEASE_PATH }}
      - name: Verify DevOps Artifact exists
        run: |
          if [ -f "${{ env.KUI_ARTIFACT_RELEASE_PATH }}/${{ env.KUI_ARTIFACT_ZIP_NAME }}_${{ env.KUI_ARTIFACT_VERSION }}.zip" ]; then
            echo "DevOps Artifact ${{ env.KUI_ARTIFACT_ZIP_NAME }}_${{ env.KUI_ARTIFACT_VERSION }}.zip exists"
          else
            echo "DevOps Artifact ${{ env.KUI_ARTIFACT_ZIP_NAME }}_${{ env.KUI_ARTIFACT_VERSION }}.zip is missing"
            exit 1
          fi
      - name: List KUI_ARTIFACT_RELEASE_PATH project files recursively
        run: ls -lRh ${{ env.KUI_ARTIFACT_RELEASE_PATH }}

  release-dev:
    needs: build
    runs-on: ubuntu-latest
    env:
      name: Development
      AZURE_CLIENT_ID: ${{ secrets.KUI_SPN_DEV_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.KUI_SPN_DEV_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.KUI_SPN_DEV_TENANT_ID }}
      KUI_FUNCTION_APP_NAME: ${{ vars.KUI_DEV_FUNCTION_APP_01_NAME }}
      KUI_RG: ${{ vars.KUI_DEV_RG }}
    steps:
      - name: Download Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.KUI_ARTIFACT_ZIP_NAME }}
          path: ${{ github.workspace }}/release
      - name: List release artifact files
        run: ls -lRh ${{ github.workspace }}/release
      - name: Deploy to Azure Functions
        run: |
          az login --service-principal --username ${{ env.AZURE_CLIENT_ID }} --password=${{ env.AZURE_CLIENT_SECRET }} --tenant ${{ env.AZURE_TENANT_ID }}
          bash ${{ env.KUI_SCRIPT_STAGE_1 }}
          RG="${{ env.KUI_RG }}" FUNCTION_APP_NAME="${{ env.KUI_FUNCTION_APP_NAME }}" PACKAGE_PATH="${{ env.KUI_ARTIFACT_RELEASE_PATH }}/${{ env.KUI_ARTIFACT_ZIP_NAME }}_${{ env.KUI_ARTIFACT_VERSION }}.zip" bash ${{ env.KUI_SCRIPT_STAGE_2 }}
          RG="${{ env.KUI_RG }}" FUNCTION_APP_NAME="${{ env.KUI_FUNCTION_APP_NAME }}" bash ${{ env.KUI_SCRIPT_STAGE_3 }}
          RG="${{ env.KUI_RG }}" FUNCTION_APP_NAME="${{ env.KUI_FUNCTION_APP_NAME }}" bash ${{ env.KUI_SCRIPT_STAGE_4 }}


  release-tst:
    needs: release-dev
    runs-on: ubuntu-latest
    env:
      name: Test
      AZURE_CLIENT_ID: ${{ secrets.KUI_SPN_TST_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.KUI_SPN_TST_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.KUI_SPN_TST_TENANT_ID }}
      KUI_FUNCTION_APP_NAME: ${{ vars.KUI_TST_FUNCTION_APP_01_NAME }}
      KUI_RG: ${{ vars.KUI_TST_RG }}
    steps:
      - name: Download Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.KUI_ARTIFACT_ZIP_NAME }}
          path: ${{ github.workspace }}/release
      - name: List release artifact files
        run: ls -lRh ${{ github.workspace }}/release
      - name: Deploy to Azure Functions
        run: |
          az login --service-principal --username ${{ env.AZURE_CLIENT_ID }} --password=${{ env.AZURE_CLIENT_SECRET }} --tenant ${{ env.AZURE_TENANT_ID }}
          bash ${{ env.KUI_SCRIPT_STAGE_1 }}
          RG="${{ env.KUI_RG }}" FUNCTION_APP_NAME="${{ env.KUI_FUNCTION_APP_NAME }}" PACKAGE_PATH="${{ env.KUI_ARTIFACT_RELEASE_PATH }}/${{ env.KUI_ARTIFACT_ZIP_NAME }}_${{ env.KUI_ARTIFACT_VERSION }}.zip" bash ${{ env.KUI_SCRIPT_STAGE_2 }}
          RG="${{ env.KUI_RG }}" FUNCTION_APP_NAME="${{ env.KUI_FUNCTION_APP_NAME }}" bash ${{ env.KUI_SCRIPT_STAGE_3 }}
          RG="${{ env.KUI_RG }}" FUNCTION_APP_NAME="${{ env.KUI_FUNCTION_APP_NAME }}" bash ${{ env.KUI_SCRIPT_STAGE_4 }}
