name: Build HttpTriggerPostExperiment

on:
  push:
    branches:
      - develop
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  KUI_SOLUTION: HttpPostExperiment.sln
  KUI_SOLUTION_PROJECT: HttpPostExperiment.csproj
  KUI_SOLUTION_BUILD_CONFIGURATION: Release
  KUI_SOLUTION_TEST_PROJECT: ${{ github.workspace }}/tests/HttpTriggerPostExperimentTests/HttpTriggerPostExperimentTests.csproj
  KUI_SOLUTION_SOURCE_PATH: ${{ github.workspace }}/src/functions/HttpPostExperiment
  KUI_SOLUTION_WORK_PATH: ${{ github.workspace }}/http_post_exp_function_app
  KUI_SOLUTION_BUILD_PATH: ${{ github.workspace }}/http_post_exp_function_app/build
  KUI_SOLUTION_ARTIFACTS_PATH: ${{ github.workspace }}/artifacts

  KUI_ARTIFACT_VERSION: 1.0.${{ github.run_number }}
  KUI_ARTIFACT_RELEASE_PATH: ${{ github.workspace }}/release
  KUI_ARTIFACT_ZIP_NAME: http-post-exp-fa-package

  KUI_SCRIPT_STAGE_1: ${{ github.workspace }}/release/Scripts/http-post-exp-stage-1.sh
  KUI_SCRIPT_STAGE_2: ${{ github.workspace }}/release/Scripts/http-post-exp-stage-2.sh
  KUI_SCRIPT_STAGE_3: ${{ github.workspace }}/release/Scripts/http-post-exp-stage-3.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare KUI_SOLUTION_WORK_PATH directory
        run: mkdir -p ${{ env.KUI_SOLUTION_WORK_PATH }}
      - name: Prepare KUI_SOLUTION_ARTIFACTS_PATH directory
        run: mkdir -p ${{ env.KUI_SOLUTION_ARTIFACTS_PATH }}
      - name: Prepare KUI_ARTIFACT_RELEASE_PATH directory
        run: mkdir -p ${{ env.KUI_ARTIFACT_RELEASE_PATH }}
      - name: Dotnet Clean
        run: dotnet clean ${{ env.KUI_SOLUTION }}
      - name: Dotnet Restore
        run: dotnet restore ${{ env.KUI_SOLUTION }}
      - name: Dotnet Build
        run: dotnet build ${{ env.KUI_SOLUTION }} -c ${{ env.KUI_SOLUTION_BUILD_CONFIGURATION }} --no-restore
      - name: Run Unit Tests
        run: dotnet test ${{ env.KUI_SOLUTION_TEST_PROJECT }} --configuration ${{ env.KUI_SOLUTION_BUILD_CONFIGURATION }}
      - name: Copy function app files
        run: |
          cp -a ${{ github.workspace }}/Directory.Build.props ${{ env.KUI_SOLUTION_WORK_PATH }}/Directory.Build.props
          mkdir -p ${{ env.KUI_SOLUTION_WORK_PATH }}/src/aspire
          cp -a ${{ github.workspace }}/src/aspire ${{ env.KUI_SOLUTION_WORK_PATH }}/src/aspire
          mkdir -p ${{ env.KUI_SOLUTION_WORK_PATH }}/src/shared
          cp -a ${{ github.workspace }}/src/shared ${{ env.KUI_SOLUTION_WORK_PATH }}/src/shared
          mkdir -p ${{ env.KUI_SOLUTION_WORK_PATH }}/src/functions
          cp -a ${{ github.workspace }}/src/functions ${{ env.KUI_SOLUTION_WORK_PATH }}/src/functions
      - name: Dotnet Restore
        run: dotnet restore ${{ env.KUI_SOLUTION_SOURCE_PATH }}/${{ env.KUI_SOLUTION_PROJECT }}
      - name: Dotnet Publish
        run: dotnet publish ${{ env.KUI_SOLUTION_SOURCE_PATH }}/${{ env.KUI_SOLUTION_PROJECT }} -c ${{ env.KUI_SOLUTION_BUILD_CONFIGURATION }} -o ${{ env.KUI_SOLUTION_BUILD_PATH }}
      - name: Create deployment package
        run: |
          cd ${{ env.KUI_SOLUTION_BUILD_PATH }}
          zip -r ${{ env.KUI_ARTIFACT_RELEASE_PATH }}/${{ env.KUI_ARTIFACT_ZIP_NAME }}_${{ env.KUI_ARTIFACT_VERSION }}.zip .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KUI_ARTIFACT_ZIP_NAME }}
          path: ${{ env.KUI_ARTIFACT_RELEASE_PATH }}
      - name: Verify DevOps Artifact exists
        run: |
          if [ -f "${{ env.KUI_ARTIFACT_RELEASE_PATH }}/${{ env.KUI_ARTIFACT_ZIP_NAME }}_${{ env.KUI_ARTIFACT_VERSION }}.zip" ]; then
            echo "DevOps Artifact ${{ env.KUI_ARTIFACT_ZIP_NAME }}_${{ env.KUI_ARTIFACT_VERSION }}.zip exists"
          else
            echo "DevOps Artifact ${{ env.KUI_ARTIFACT_ZIP_NAME }}_${{ env.KUI_ARTIFACT_VERSION }}.zip is missing"
            exit 1
          fi
      - name: List KUI_ARTIFACT_RELEASE_PATH project files recursively
        run: ls -lRh ${{ env.KUI_ARTIFACT_RELEASE_PATH }}
